import * as XLSX from 'xlsx';
import { format } from 'date-fns';
import type { SoaExportStrings, SoaPayload } from './types';
import { CSC_STATUSES, CSC_STATUS_TO_VALUE } from '@/lib/csc/csc-statuses';

// English fallbacks — used when meta.strings is not provided
const FALLBACK: SoaExportStrings = {
  docTitle: 'Statement of Applicability',
  organisation: 'Organisation',
  dateOfExport: 'Date of Export',
  frameworkLabel: 'Framework',
  statusLegend: 'Status Legend',
  colCode: 'Code',
  colSection: 'Section',
  colControl: 'Control',
  colRequirements: 'Requirements',
  colStatus: 'Status',
  colLevel: 'Level',
  colMeaning: 'Meaning',
  total: 'Total',
  generatedBy: 'Generated by Unicis Platform',
  controls: 'controls',
  legendSheetTitle: 'Unicis Control Status Maturity Scale',
};

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = Object.assign(document.createElement('a'), {
    href: url,
    download: filename,
  });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadSoaOds(payload: SoaPayload): void {
  const { meta, rows } = payload;
  const str = { ...FALLBACK, ...meta.strings };

  const wb = XLSX.utils.book_new();

  // ── Sheet 1: SoA ──────────────────────────────────────────────────────────
  const soaHeader = [
    str.colCode,
    str.colSection,
    str.colControl,
    str.colRequirements,
    str.colStatus,
  ];

  const soaData = rows.map((row) => [
    row.code,
    row.section,
    row.control,
    row.requirements,
    row.statusLabel,
  ]);

  // Title rows + header + data + summary
  const titleRows: (string | number)[][] = [
    [`${str.docTitle} — ${meta.framework}`],
    [
      `${str.organisation}: ${meta.teamName}`,
      '',
      `${str.dateOfExport}: ${format(meta.dateOfExport, 'dd MMM yyyy HH:mm')}`,
    ],
    [`${str.frameworkLabel}: ${meta.framework}`],
    [], // spacer
    soaHeader,
    ...soaData,
  ];

  // Summary row
  const counts = CSC_STATUSES.map(
    (s) =>
      `${meta.statusLabelMap?.[s] ?? s}: ${rows.filter((r) => r.status === s).length}`
  ).join('   |   ');
  titleRows.push([`${str.total}: ${rows.length}   |   ${counts}`]);

  const ws = XLSX.utils.aoa_to_sheet(titleRows);
  ws['!cols'] = [
    { wch: 12 },
    { wch: 30 },
    { wch: 40 },
    { wch: 60 },
    { wch: 28 },
  ];

  XLSX.utils.book_append_sheet(wb, ws, str.docTitle);

  // ── Sheet 2: Legend ────────────────────────────────────────────────────────
  const legendData: (string | number)[][] = [
    [str.legendSheetTitle],
    [str.colLevel, str.colStatus, str.colMeaning],
    ...CSC_STATUSES.map((s) => [
      CSC_STATUS_TO_VALUE[s],
      meta.statusLabelMap?.[s] ?? s,
      meta.statusMeaningMap?.[s] ?? '',
    ]),
  ];

  const legendWs = XLSX.utils.aoa_to_sheet(legendData);
  legendWs['!cols'] = [{ wch: 8 }, { wch: 30 }, { wch: 65 }];

  XLSX.utils.book_append_sheet(wb, legendWs, str.statusLegend);

  // Write and download
  const buf = XLSX.write(wb, { bookType: 'ods', type: 'array' });
  const blob = new Blob([buf], {
    type: 'application/vnd.oasis.opendocument.spreadsheet',
  });
  triggerDownload(
    blob,
    `SoA_${meta.iso}_${format(meta.dateOfExport, 'yyyy-MM-dd')}.ods`
  );
}
