import ExcelJS from 'exceljs';
import { format } from 'date-fns';
import type { SoaExportStrings, SoaPayload } from './types';
import { CSC_STATUSES, CSC_STATUS_TO_VALUE } from '@/lib/csc/csc-statuses';

// Colours match CSC_STATUS_TO_CSS exactly
const STATUS_STYLE: Record<string, { bg: string; fg: string }> = {
  'unknown':                   { bg: 'E2E8F0', fg: '475569' },
  'not-applicable':            { bg: 'B2B2B2', fg: 'FFFFFF' },
  'not-performed':             { bg: 'FF0000', fg: 'FFFFFF' },
  'performed-informally':      { bg: 'CA003F', fg: 'FFFFFF' },
  'planned':                   { bg: '666666', fg: 'FFFFFF' },
  'well-defined':              { bg: 'FFBE00', fg: '1a1a1a' },
  'quantitatively-controlled': { bg: '6AD900', fg: '1a1a1a' },
  'continuously-improving':    { bg: '2F8F00', fg: 'FFFFFF' },
};

// English fallbacks — used when meta.strings is not provided
const FALLBACK: SoaExportStrings = {
  docTitle:         'Statement of Applicability',
  organisation:     'Organisation',
  dateOfExport:     'Date of Export',
  frameworkLabel:   'Framework',
  statusLegend:     'Status Legend',
  colCode:          'Code',
  colSection:       'Section',
  colControl:       'Control',
  colRequirements:  'Requirements',
  colStatus:        'Status',
  colLevel:         'Level',
  colMeaning:       'Meaning',
  total:            'Total',
  generatedBy:      'Generated by Unicis Platform',
  controls:         'controls',
  legendSheetTitle: 'Unicis Control Status Maturity Scale',
};

function argb(hex: string) { return `FF${hex.toUpperCase()}`; }
function fill(hex: string): ExcelJS.Fill {
  return { type: 'pattern', pattern: 'solid', fgColor: { argb: argb(hex) } };
}
function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a   = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function downloadSoaXlsx(payload: SoaPayload): Promise<void> {
  const { meta, rows } = payload;
  const str = { ...FALLBACK, ...meta.strings };

  const wb = new ExcelJS.Workbook();
  wb.creator = 'Unicis Platform';

  // ── Sheet 1: SoA ──────────────────────────────────────────────────────────
  const ws = wb.addWorksheet(str.docTitle, {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true },
  });

  // Column widths: Code, Section, Control, Requirements, Status
  [12, 30, 40, 60, 28].forEach((w, i) => { ws.getColumn(i + 1).width = w; });

  // Title
  ws.mergeCells('A1:E1');
  const t1 = ws.getCell('A1');
  t1.value     = `${str.docTitle} — ${meta.framework}`;
  t1.font      = { bold: true, size: 14, color: { argb: 'FFFFFFFF' } };
  t1.fill      = fill('0052cc');
  t1.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 };
  ws.getRow(1).height = 34;

  // Metadata
  ws.mergeCells('A2:B2');
  ws.getCell('A2').value = `${str.organisation}: ${meta.teamName}`;
  ws.getCell('A2').fill  = fill('EBF2FA');
  ws.getCell('A2').font  = { bold: true, size: 10 };
  ws.mergeCells('C2:E2');
  ws.getCell('C2').value     = `${str.dateOfExport}: ${format(meta.dateOfExport, 'dd MMM yyyy HH:mm')}`;
  ws.getCell('C2').fill      = fill('EBF2FA');
  ws.getCell('C2').font      = { size: 9, italic: true };
  ws.getCell('C2').alignment = { horizontal: 'right' };
  ws.mergeCells('A3:B3');
  ws.getCell('A3').value = `${str.frameworkLabel}: ${meta.framework}`;
  ws.getCell('A3').fill  = fill('EBF2FA');
  ws.getCell('A3').font  = { size: 9, italic: true };
  ws.getRow(4).height = 5;

  // Column headers
  [str.colCode, str.colSection, str.colControl, str.colRequirements, str.colStatus].forEach((label, i) => {
    const cell     = ws.getCell(5, i + 1);
    cell.value     = label;
    cell.font      = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 };
    cell.fill      = fill('00398f');
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border    = { bottom: { style: 'medium', color: { argb: 'FF1A3C5E' } } };
  });
  ws.getRow(5).height = 24;

  // Data rows
  rows.forEach((row, idx) => {
    const r     = idx + 6;
    const style = STATUS_STYLE[row.status] ?? STATUS_STYLE['unknown'];
    const alt   = idx % 2 === 1;

    // Render status label but use status code for colouring
    [row.code, row.section, row.control, row.requirements, row.statusLabel].forEach((v, ci) => {
      const cell     = ws.getCell(r, ci + 1);
      cell.value     = v;
      cell.alignment = { wrapText: true, vertical: 'top' };
      cell.border    = {
        bottom: { style: 'thin', color: { argb: 'FFD0D7DE' } },
        right:  { style: 'thin', color: { argb: 'FFD0D7DE' } },
      };
      if (ci === 4) {
        cell.fill      = fill(style.bg);
        cell.font      = { bold: true, color: { argb: argb(style.fg) }, size: 9 };
        cell.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
      } else {
        cell.fill = fill(alt ? 'F5F8FA' : 'FFFFFF');
        cell.font = { size: 9 };
      }
    });
    ws.getRow(r).height = 40;
  });

  // Summary
  const sumR = rows.length + 6;
  ws.mergeCells(`A${sumR}:E${sumR}`);
  const counts = CSC_STATUSES
    .map((s) => `${meta.statusLabelMap?.[s] ?? s}: ${rows.filter((r) => r.status === s).length}`)
    .join('   |   ');
  ws.getCell(`A${sumR}`).value  = `${str.total}: ${rows.length}   |   ${counts}`;
  ws.getCell(`A${sumR}`).font   = { italic: true, size: 8 };
  ws.getCell(`A${sumR}`).fill   = fill('E8EFF5');
  ws.getRow(sumR).height        = 16;

  ws.views      = [{ state: 'frozen', ySplit: 5 }];
  ws.autoFilter = { from: 'A5', to: 'E5' };

  // ── Sheet 2: Legend ────────────────────────────────────────────────────────
  const leg = wb.addWorksheet(str.statusLegend);
  [8, 30, 65].forEach((w, i) => { leg.getColumn(i + 1).width = w; });

  leg.mergeCells('A1:C1');
  leg.getCell('A1').value     = str.legendSheetTitle;
  leg.getCell('A1').font      = { bold: true, size: 13, color: { argb: 'FFFFFFFF' } };
  leg.getCell('A1').fill      = fill('0052cc');
  leg.getCell('A1').alignment = { horizontal: 'center', vertical: 'middle' };
  leg.getRow(1).height        = 28;

  [str.colLevel, str.colStatus, str.colMeaning].forEach((h, i) => {
    const c = leg.getCell(2, i + 1);
    c.value     = h;
    c.font      = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 };
    c.fill      = fill('2C6E9B');
    c.alignment = { horizontal: 'center', vertical: 'middle' };
  });
  CSC_STATUSES.forEach((s, i) => {
    const style = STATUS_STYLE[s] ?? { bg: 'FFFFFF', fg: '000000' };
    const r     = i + 3;
    const label = meta.statusLabelMap?.[s] ?? s;
    const meaning = meta.statusMeaningMap?.[s] ?? '';
    [CSC_STATUS_TO_VALUE[s], label, meaning].forEach((v, ci) => {
      const c     = leg.getCell(r, ci + 1);
      c.value     = v;
      c.fill      = fill(style.bg);
      c.font      = { color: { argb: argb(style.fg) }, bold: ci === 1, size: 10 };
      c.alignment = { vertical: 'middle', horizontal: ci === 0 ? 'center' : 'left' };
      c.border    = { bottom: { style: 'thin', color: { argb: 'FFD0D7DE' } } };
    });
    leg.getRow(r).height = 22;
  });

  const buf  = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  triggerDownload(blob, `SoA_${meta.iso}_${format(meta.dateOfExport, 'yyyy-MM-dd')}.xlsx`);
}
