import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { SoaExportStrings, SoaPayload } from './types';
import { CSC_STATUSES, CSC_STATUS_TO_VALUE } from '@/lib/csc/csc-statuses';

// RGB tuples matching CSC_STATUS_TO_CSS
type RGB = [number, number, number];
const STATUS_BG: Record<string, RGB> = {
  'unknown':                   [226, 232, 240],
  'not-applicable':            [178, 178, 178],
  'not-performed':             [255,   0,   0],
  'performed-informally':      [202,   0,  63],
  'planned':                   [102, 102, 102],
  'well-defined':              [255, 190,   0],
  'quantitatively-controlled': [106, 217,   0],
  'continuously-improving':    [ 47, 143,   0],
};
const STATUS_FG: Record<string, RGB> = {
  'unknown':                   [ 71,  85, 105],
  'well-defined':              [ 26,  26,  26],
  'quantitatively-controlled': [ 26,  26,  26],
};
const defaultFg: RGB = [255, 255, 255];

// English fallbacks — used when meta.strings is not provided
const FALLBACK: SoaExportStrings = {
  docTitle:         'Statement of Applicability',
  organisation:     'Organisation',
  dateOfExport:     'Date of Export',
  frameworkLabel:   'Framework',
  statusLegend:     'Status Legend',
  colCode:          'Code',
  colSection:       'Section',
  colControl:       'Control',
  colRequirements:  'Requirements',
  colStatus:        'Status',
  colLevel:         'Level',
  colMeaning:       'Meaning',
  total:            'Total',
  generatedBy:      'Generated by Unicis Platform',
  controls:         'controls',
  legendSheetTitle: 'Unicis Control Status Maturity Scale',
};

function statusFg(st: string): RGB { return STATUS_FG[st] ?? defaultFg; }

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a   = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadSoaPdf(payload: SoaPayload): void {
  const { meta, rows } = payload;
  const str = { ...FALLBACK, ...meta.strings };

  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });

  const pageW  = doc.internal.pageSize.getWidth();
  const margin = 30;
  let y = margin;

  // ── Title bar ──────────────────────────────────────────────────────────────
  doc.setFillColor(0, 67, 168);
  doc.rect(margin, y, pageW - margin * 2, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(`${str.docTitle} — ${meta.framework}`, margin + 8, y + 18);
  y += 48;

  // ── Meta line ──────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(30, 30, 50);
  doc.text(`${str.organisation}: ${meta.teamName}`, margin, y);
  doc.text(
    `${str.dateOfExport}: ${format(meta.dateOfExport, 'dd MMM yyyy HH:mm')}`,
    pageW - margin,
    y,
    { align: 'right' }
  );
  y += 14;

  // ── Controls table via autoTable ──────────────────────────────────────────
  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [[str.colCode, str.colSection, str.colControl, str.colRequirements, str.colStatus]],
    body: rows.map((r) => [r.code, r.section, r.control, r.requirements, r.status]),
    styles: { fontSize: 7, cellPadding: 4, valign: 'top', overflow: 'linebreak' },
    headStyles: { fillColor: [17, 47, 117], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 45 },
      1: { cellWidth: 95 },
      2: { cellWidth: 130 },
      3: { cellWidth: 'auto' },
      4: { cellWidth: 95, halign: 'center' },
    },
    alternateRowStyles: { fillColor: [245, 248, 250] },
    // Colour the Status cell per maturity level
    didParseCell(data) {
      if (data.section === 'body' && data.column.index === 4) {
        // Use the row index to lookup the original status code/label
        const rowIndex = data.row.index;
        const statusCode = rows[rowIndex]?.status ?? 'unknown';
        const statusLabel = rows[rowIndex]?.statusLabel ?? String(data.cell.raw);
        const bg     = STATUS_BG[statusCode] ?? STATUS_BG['unknown'];
        const fg     = statusFg(statusCode);
        data.cell.styles.fillColor    = bg;
        data.cell.styles.textColor    = fg;
        data.cell.styles.fontStyle    = 'bold';
        // Replace the displayed text with the localized label
        data.cell.text = String(statusLabel);
      }
    },
    didDrawPage() {
      // Page footer
      doc.setFontSize(6.5);
      doc.setTextColor(150, 150, 150);
      doc.setFont('helvetica', 'normal');
      doc.text(
        `${str.generatedBy}  •  ${format(meta.dateOfExport, 'dd MMM yyyy HH:mm')}`,
        pageW / 2,
        doc.internal.pageSize.getHeight() - 15,
        { align: 'center' }
      );
    },
  });

  // ── Summary counts ────────────────────────────────────────────────────────
  const finalY = (doc as any).lastAutoTable.finalY + 6;
  doc.setFontSize(7);
  doc.setTextColor(80, 80, 100);
  doc.setFont('helvetica', 'italic');
  const counts = CSC_STATUSES
    .map((s) => `${meta.statusLabelMap?.[s] ?? s}: ${rows.filter((r) => r.status === s).length}`)
    .join('  ·  ');
  doc.text(`${str.total}: ${rows.length}  ·  ${counts}`, margin, finalY);

  // ── Legend ────────────────────────────────────────────────────────────────
  const legendY = finalY + 12;
  const bw      = Math.floor((pageW - margin * 2) / CSC_STATUSES.length) - 2;
  let lx        = margin;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(26, 60, 94);
  doc.text(`${str.statusLegend}:`, margin, legendY);

  CSC_STATUSES.forEach((s) => {
    const bg = STATUS_BG[s] ?? ([200, 200, 200] as RGB);
    const fg = statusFg(s);
    const label = meta.statusLabelMap?.[s] ?? s;
    doc.setFillColor(...bg);
    doc.rect(lx, legendY + 4, bw, 14, 'F');
    doc.setTextColor(...fg);
    doc.setFontSize(5.5);
    doc.text(`${CSC_STATUS_TO_VALUE[s]} · ${label}`, lx + bw / 2, legendY + 13, { align: 'center' });
    lx += bw + 2;
  });

  const blob = doc.output('blob');
  triggerDownload(blob, `SoA_${meta.iso}_${format(meta.dateOfExport, 'yyyy-MM-dd')}.pdf`);
}
