import type { ISO } from 'types';
import type { CscStatus } from '@/lib/csc/csc-statuses';

export interface SoaRow {
  code:         string;
  section:      string;
  control:      string;
  requirements: string;
  // status code (one of the CscStatus values) — used for colouring/counts
  status:       CscStatus | 'unknown';
  // human readable, localized label for the status (resolved in the component)
  statusLabel:  string;
  // human readable, localized meaning/description for the status
  meaning?:     string;
}

export type ExportFormat = 'xlsx' | 'pdf' | 'html';

/** Keys for all UI strings that appear in exported documents (HTML, PDF, XLSX). */
export interface SoaExportStrings {
  docTitle:        string; // "Statement of Applicability"
  organisation:    string; // "Organisation"
  dateOfExport:    string; // "Date of Export"
  frameworkLabel:  string; // "Framework"
  statusLegend:    string; // "Status Legend"
  colCode:         string; // "Code"
  colSection:      string; // "Section"
  colControl:      string; // "Control"
  colRequirements: string; // "Requirements"
  colStatus:       string; // "Status"
  colLevel:        string; // "Level"
  colMeaning:      string; // "Meaning"
  total:           string; // "Total"
  generatedBy:     string; // "Generated by Unicis Platform"
  controls:        string; // "controls"
  legendSheetTitle: string; // "Unicis Control Status Maturity Scale"
}

export interface SoaMeta {
  teamName:        string;
  framework:       string; // e.g. "MVSP v1.0-20211007"
  iso:             ISO;    // e.g. "mvps"
  dateOfExport:    Date;
  // localized status labels/descriptions (resolved in the component via t())
  statusLabelMap?:   Record<string, string>;
  statusMeaningMap?: Record<string, string>;
  // localized document-level UI strings (resolved in the component via t())
  strings?:          SoaExportStrings;
}

/** @deprecated Use SoaMeta directly — statusLabelMap and statusMeaningMap are now on SoaMeta. */
export interface SoaMetaExtras {
  statusLabelMap?: Record<string, string>;
  statusMeaningMap?: Record<string, string>;
}

export interface SoaPayload {
  meta: SoaMeta;
  rows: SoaRow[];
}