stages:
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  CAPROVER_APP_NAME: "platform"
  CAPROVER_DEV_URL: "https://captain.dev.unicis.tech"  
  CAPROVER_PROD_URL: "https://captain.platform.unicis.tech"

test:
  stage: test
  image: node:18.18.2
  script:
    - echo 'test passed'
  only:
    - merge_requests
  except:
    - tags

deploy_dev:
  stage: deploy
  image: node:18.18.2
  before_script:
    - npm install -g caprover
  script:
    - echo "Deploying branch $CI_COMMIT_REF_NAME "
    - caprover deploy --caproverUrl "$CAPROVER_DEV_URL" --caproverPassword "$CAPROVER_DEV_PASSWORD" --caproverApp "$CAPROVER_APP_NAME" --branch "$CI_COMMIT_REF_NAME"
  only:
    - merge_requests
  except:
    - tags
  environment:
    name: development
  when: manual

deploy_prod:
  stage: deploy
  image: node:18.18.2
  before_script:
    - npm install -g caprover
  script:
    - caprover deploy --caproverUrl "$CAPROVER_PROD_URL" --caproverPassword "$CAPROVER_PROD_PASSWORD" --caproverApp "$CAPROVER_APP_NAME" --branch main
  only:
    - tags
  environment:
    name: production
    url: https://${CAPROVER_APP_NAME}.platform.unicis.tech