stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  CAPROVER_APP_NAME: "platform"
  CAPROVER_DEV_URL: "https://captain.dev.unicis.tech"  
  CAPROVER_PROD_URL: "https://captain.platform.unicis.tech"


test:
  stage: test
  image: node:18.18.2
  script:
    - echo 'test passed'
  only:
    - merge_requests
  except:
    - tags

build_dev:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f Dockerfile.local -t $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_SHORT_SHA .
    - docker tag $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:dev-latest
    - docker push $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:dev-latest
  only:
    - merge_requests
  except:
    - tags

build_prod:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f Dockerfile.local -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - tags

deploy_dev:
  stage: deploy
  image: node:18.18.2
  before_script:
    - npm install -g caprover
  script:
    - caprover deploy --caproverUrl $CAPROVER_DEV_URL --caproverPassword $CAPROVER_DEV_PASSWORD --caproverApp $CAPROVER_APP_NAME --imageName $CI_REGISTRY_IMAGE:dev-$CI_COMMIT_SHORT_SHA
  only:
    - merge_requests
  except:
    - tags
  environment:
    name: development
    url: https://${CAPROVER_APP_NAME}.dev.unicis.tech
  when: manual

deploy_prod:
  stage: deploy
  image: node:18.18.2
  before_script:
    - npm install -g caprover
  script:
    - caprover deploy --caproverUrl $CAPROVER_PROD_URL --caproverPassword $CAPROVER_PROD_PASSWORD --caproverApp $CAPROVER_APP_NAME --imageName $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
  environment:
    name: production
    url: https://${CAPROVER_APP_NAME}.platform.unicis.tech