FROM node:20-bookworm

ENV NODE_ENV=development

WORKDIR /app

COPY . .
COPY .env.example .env
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

EXPOSE 3000

RUN chmod +x entrypoint.sh

ENTRYPOINT ["sh", "./entrypoint.sh"]
