module.exports = {
  mode: 'jit',
  darkMode: ['class', 'class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    'node_modules/daisyui/dist/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        /* Direction B semantic colors */
        'ub-blue':        '#2563EB',
        'ub-blue-hover':  '#1D4ED8',
        'ub-blue-bg':     '#EFF6FF',
        'ub-blue-border': '#BFDBFE',
        'ub-blue-text':   '#1E3A5F',
        'ub-green':       '#16A34A',
        'ub-green-bg':    '#DCFCE7',
        'ub-green-border':'#BBF7D0',
        'ub-green-text':  '#14532D',
        'ub-amber':       '#D97706',
        'ub-amber-bg':    '#FEF3C7',
        'ub-amber-border':'#FDE68A',
        'ub-amber-text':  '#78350F',
        'ub-red':         '#DC2626',
        'ub-red-bg':      '#FEE2E2',
        'ub-red-border':  '#FECACA',
        'ub-red-text':    '#7F1D1D',
        'ub-purple':      '#7C3AED',
        'ub-purple-bg':   '#EDE9FE',
        'ub-purple-border':'#DDD6FE',
        'ub-purple-text': '#3B0764',
        'ub-yellow':      '#CA8A04',
        'ub-yellow-bg':   '#FEF9C3',
        'ub-yellow-border':'#FEF08A',
        'ub-yellow-text': '#713F12',

        /* Slate palette */
        'slate-50':       '#F8FAFC',
        'slate-100':      '#F1F5F9',
        'slate-200':      '#E2E8F0',
        'slate-300':      '#CBD5E1',
        'slate-400':      '#94A3B8',
        'slate-500':      '#64748B',
        'slate-600':      '#475569',
        'slate-700':      '#334155',
        'slate-900':      '#0F172A',

        /* Legacy risk colors */
        'risk-extreme-low': 'rgba(211, 211, 211, 0.5)',
        'risk-low': 'rgba(0, 255, 0, 0.3)',
        'risk-medium': 'rgba(255, 255, 0, 0.3)',
        'risk-high': 'rgba(255, 165, 0, 0.3)',
        'risk-extreme': 'rgba(255, 0, 0, 0.3)',
        'risk-extreme-low-dark': 'rgba(161, 161, 170, 1)',
        'risk-low-dark': 'rgba(52, 211, 153, 1)',
        'risk-medium-dark': 'rgba(251, 146, 60, 1)',
        'risk-high-dark': 'rgba(251, 146, 60, 1)',
        'risk-extreme-dark': 'rgba(239, 68, 68, 1)',

        task: {
          todo: 'rgb(232, 232, 232)',
          inprogress: 'rgb(123, 146, 178)',
          inreview: 'rgb(77, 110, 255)',
          feedback: 'rgb(0, 181, 255)',
          done: 'rgb(0, 169, 110)',
          failed: 'rgb(239, 68, 68)',
        },
      },
      borderRadius: {
        'sm':  '4px',
        'md':  '6px',
        'lg':  '8px',
        'xl':  '10px',
        '2xl': '12px',
      },
      fontSize: {
        'label': ['11px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.06em' }],
      },
    },
  },
  safelist: [
    'bg-risk-extreme-low',
    'bg-risk-low',
    'bg-risk-medium',
    'bg-risk-high',
    'bg-risk-extreme',
    'bg-risk-extreme-low-dark',
    'bg-risk-low-dark',
    'bg-risk-medium-dark',
    'bg-risk-high-dark',
    'bg-risk-extreme-dark',
    'bg-task-todo',
    'bg-task-inprogress',
    'bg-task-inreview',
    'bg-task-feedback',
    'bg-task-done',
    'bg-ub-blue',
    'bg-ub-blue-bg',
    'bg-ub-green',
    'bg-ub-green-bg',
    'bg-ub-amber',
    'bg-ub-amber-bg',
    'bg-ub-red',
    'bg-ub-red-bg',
    'bg-ub-purple',
    'bg-ub-purple-bg',
    'bg-ub-yellow',
    'bg-ub-yellow-bg',
    'text-ub-blue',
    'text-ub-blue-text',
    'text-ub-green',
    'text-ub-green-text',
    'text-ub-amber',
    'text-ub-amber-text',
    'text-ub-red',
    'text-ub-red-text',
    'text-ub-purple',
    'text-ub-purple-text',
    'text-ub-yellow',
    'text-ub-yellow-text',
  ],
};
