import ExcelJS from 'exceljs';
import { format } from 'date-fns';

// ── Shared colour / styling helpers ──────────────────────────────────────────

export type RGB = [number, number, number];

export const STATUS_BG_HEX: Record<string, string> = {
  todo: 'E8E8E8',
  inprogress: '7B92B2',
  inreview: '4D6EFF',
  feedback: '00B5FF',
  done: '00A96E',
  failed: 'EF4444',
};
export const STATUS_FG_HEX: Record<string, string> = { todo: '1a1a1a' };
export const STATUS_BG_RGB: Record<string, RGB> = {
  todo: [232, 232, 232],
  inprogress: [123, 146, 178],
  inreview: [77, 110, 255],
  feedback: [0, 181, 255],
  done: [0, 169, 110],
  failed: [239, 68, 68],
};
export const STATUS_FG_RGB: Record<string, RGB> = { todo: [26, 26, 26] };

export const DEFAULT_FG_HEX = 'FFFFFF';
export const DEFAULT_FG_RGB: RGB = [255, 255, 255];

export function getBgHex(status: string) {
  return STATUS_BG_HEX[status] ?? 'E2E8F0';
}
export function getFgHex(status: string) {
  return STATUS_FG_HEX[status] ?? DEFAULT_FG_HEX;
}
export function getBgRgb(status: string): RGB {
  return STATUS_BG_RGB[status] ?? [226, 232, 240];
}
export function getFgRgb(status: string): RGB {
  return STATUS_FG_RGB[status] ?? DEFAULT_FG_RGB;
}

export function argb(hex: string) {
  return `FF${hex.toUpperCase()}`;
}
export function fill(hex: string): ExcelJS.Fill {
  return { type: 'pattern', pattern: 'solid', fgColor: { argb: argb(hex) } };
}

export function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = Object.assign(document.createElement('a'), {
    href: url,
    download: filename,
  });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function datestamp() {
  return format(new Date(), 'yyyy-MM-dd');
}

export function timestamp() {
  return format(new Date(), 'dd MMM yyyy HH:mm');
}

/** Escape a value for safe embedding in HTML. */
export function escHtml(s: string): string {
  const el = document.createElement('span');
  el.textContent = String(s);
  return el.innerHTML;
}

/** Escape a value for CSV (double-quote wrapping). */
export function csvEsc(v: string): string {
  return `"${String(v).replace(/"/g, '""')}"`;
}

// ── XLSX shared builders ─────────────────────────────────────────────────────

export function buildXlsxHeader(
  ws: ExcelJS.Worksheet,
  title: string,
  headers: string[],
  colWidths: number[]
) {
  colWidths.forEach((w, i) => {
    ws.getColumn(i + 1).width = w;
  });

  const colCount = headers.length;
  const lastCol = String.fromCharCode(64 + colCount);

  // Title row
  ws.mergeCells(`A1:${lastCol}1`);
  const titleCell = ws.getCell('A1');
  titleCell.value = title;
  titleCell.font = { bold: true, size: 14, color: { argb: 'FFFFFFFF' } };
  titleCell.fill = fill('0052CC');
  titleCell.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 };
  ws.getRow(1).height = 34;

  // Metadata row
  const midCol = Math.ceil(colCount / 2);
  const midLetter = String.fromCharCode(64 + midCol);
  ws.mergeCells(`A2:${midLetter}2`);
  ws.getCell('A2').value = title;
  ws.getCell('A2').fill = fill('EBF2FA');
  ws.getCell('A2').font = { bold: true, size: 10 };
  if (midCol < colCount) {
    const nextLetter = String.fromCharCode(65 + midCol);
    ws.mergeCells(`${nextLetter}2:${lastCol}2`);
    ws.getCell(`${nextLetter}2`).value = `Date of Export: ${timestamp()}`;
    ws.getCell(`${nextLetter}2`).fill = fill('EBF2FA');
    ws.getCell(`${nextLetter}2`).font = { size: 9, italic: true };
    ws.getCell(`${nextLetter}2`).alignment = { horizontal: 'right' };
  }
  ws.getRow(3).height = 5;

  // Header row
  headers.forEach((label, i) => {
    const cell = ws.getCell(4, i + 1);
    cell.value = label;
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 };
    cell.fill = fill('00398F');
    cell.alignment = {
      vertical: 'middle',
      horizontal: 'center',
      wrapText: true,
    };
    cell.border = {
      bottom: { style: 'medium', color: { argb: 'FF1A3C5E' } },
    };
  });
  ws.getRow(4).height = 24;
}

export function buildXlsxFooter(
  ws: ExcelJS.Worksheet,
  rowCount: number,
  colCount: number,
  label: string
) {
  const sumR = rowCount + 5;
  const lastCol = String.fromCharCode(64 + colCount);
  ws.mergeCells(`A${sumR}:${lastCol}${sumR}`);
  ws.getCell(`A${sumR}`).value =
    `Total: ${rowCount} ${label}  |  Generated by Unicis Platform  |  ${timestamp()}`;
  ws.getCell(`A${sumR}`).font = { italic: true, size: 8 };
  ws.getCell(`A${sumR}`).fill = fill('E8EFF5');
  ws.getRow(sumR).height = 16;
  ws.views = [{ state: 'frozen', ySplit: 4 }];
  ws.autoFilter = {
    from: 'A4',
    to: `${lastCol}4`,
  };
}
