export const options = {
  RadioButton_Yes_No_Na: [
    { key: 'yes', value: 'yes' },
    { key: 'no', value: 'no' },
    { key: 'na', value: 'na' },
  ],
  RadioButton_Yes_No: [
    { key: 'yes', value: 'yes' },
    { key: 'no', value: 'no' },
  ],
  RadioButton_1_0: [
    { key: 'yes', value: '1' },
    { key: 'no', value: '0' },
  ],
  RadioButton_2_0: [
    { key: 'yes', value: '2' },
    { key: 'no', value: '0' },
  ],
  RadioButton_3_0: [
    { key: 'Yes', value: '3' },
    { key: 'No', value: '0' },
  ],
  RadioButton_4_0: [
    { key: 'yes', value: '4' },
    { key: 'no', value: '0' },
  ],
};

export const config = {
  EncryptionInTransit: options['RadioButton_Yes_No_Na'],
  TransferMechanism: options['RadioButton_Yes_No_Na'],
  LawfulAccess: options['RadioButton_Yes_No_Na'],
  MassSurveillanceTelecommunications: options['RadioButton_Yes_No_Na'],
  SelfReportingObligations: options['RadioButton_Yes_No_Na'],
  WarrantsSubpoenas: options['RadioButton_1_0'],
  ViolationLocalLaw: options['RadioButton_1_0'],
  HighViolationLocalLaw: options['RadioButton_2_0'],
  HighViolationDataIssue: options['RadioButton_2_0'],
  InvestigatingImporter: options['RadioButton_2_0'],
  PastWarrantSubpoena: options['RadioButton_3_0'],
  DataIssueInvestigation: options['RadioButton_2_0'],
  LocalIssueWarrants: options['RadioButton_2_0'],
  LocalMassSurveillance: options['RadioButton_3_0'],
  LocalAccessMassSurveillance: options['RadioButton_1_0'],
  LocalRoutinelyMonitor: options['RadioButton_2_0'],
  PassMassSurveillance: options['RadioButton_4_0'],
  PassMassSurveillanceConnection: options['RadioButton_4_0'],
  ImporterObligation: options['RadioButton_2_0'],
  LocalSelfReporting: options['RadioButton_2_0'],
  PastSelfReporting: options['RadioButton_4_0'],
  AssessmentProduceReport: options['RadioButton_4_0'],
  ConnectionTargetedAccess: options['RadioButton_Yes_No'],
  ConnectionSurveillanceTele: options['RadioButton_Yes_No'],
  ConnectionSelfreportingObligations: options['RadioButton_Yes_No'],
};

export const steps = [
  'transferScenario',
  'problematicLawfulAccess',
  'risk',
  'probability',
  'conclusion',
];

export const fields = [
  'DataExporter',
  'CountryDataExporter',
  'DataImporter',
  'CountryDataImporter',
  'TransferScenario',
  'DataAtIssue',
  'HowDataTransfer',
  'StartDateAssessment',
  'AssessmentYears',
  'EndDateAssessment',
  'LawImporterCountry',
  'EncryptionInTransit',
  'ReasonEncryptionInTransit',
  'TransferMechanism',
  'ReasonTransferMechanism',
  'LawfulAccess',
  'ReasonLawfulAccess',
  'MassSurveillanceTelecommunications',
  'ReasonMassSurveillanceTelecommunications',
  'SelfReportingObligations',
  'ReasonSelfReportingObligations',
  'WarrantsSubpoenas',
  'ReasonWarrantsSubpoenas',
  'ViolationLocalLaw',
  'ReasonViolationLocalLaw',
  'HighViolationLocalLaw',
  'ReasonHighViolationLocalLaw',
  'HighViolationDataIssue',
  'ReasonHighViolationDataIssue',
  'InvestigatingImporter',
  'ReasonInvestigatingImporter',
  'PastWarrantSubpoena',
  'ReasonPastWarrantSubpoena',
  'DataIssueInvestigation',
  'ReasonDataIssueInvestigation',
  'LocalIssueWarrants',
  'ReasonLocalIssueWarrants',
  'LocalMassSurveillance',
  'ReasonLocalMassSurveillance',
  'LocalAccessMassSurveillance',
  'ReasonLocalAccessMassSurveillance',
  'LocalRoutinelyMonitor',
  'ReasonLocalRoutinelyMonitor',
  'PassMassSurveillance',
  'ReasonPassMassSurveillance',
  'PassMassSurveillanceConnection',
  'ReasonPassMassSurveillanceConnection',
  'ImporterObligation',
  'ReasonImporterObligation',
  'LocalSelfReporting',
  'ReasonLocalSelfReporting',
  'PastSelfReporting',
  'ReasonPastSelfReporting',
  'AssessmentProduceReport',
  'ReasonAssessmentProduceReport',
  'RelevantDataTransferImporter',
  'ProbabilityDataTransferImporter',
  'ReasonDataTransferImporter',
  'RelevantTransferToImporter',
  'ProbabilityTransferToImporter',
  'ReasonTransferToImporter',
  'RelevantTransferToImporterForPerformance',
  'ProbabilityTransferToImporterPerformance',
  'ReasonTransferToImporterPerformance',
  'RelevantLegalGround',
  'ProbabilityLegalGround',
  'ReasonLegalGround',
  'ConnectionTargetedAccess',
  'ReasonConnectionTargetedAccess',
  'ConnectionSurveillanceTele',
  'ReasonConnectionSurveillanceTele',
  'ConnectionSelfreportingObligations',
  'ReasonConnectionSelfreportingObligations',
] as const;

export const questions = [
  'DataTransferImporter',
  'TransferToImporter',
  'TransferToImporterForPerformance',
  'LegalGround',
];
