export const config = {
    category: [
        "marital",
        "master",
        "audio",
        "video",
        "images",
        "life",
        "economic",
        "connectiondata",
        "location",
        "ssn",
        "none",
    ],
    specialCategory: [
        "none",
        "racial",
        "political",
        "religion",
        "tradeunion",
        "genetic",
        "biometric",
        "health",
        "orientation",
        "criminal",
    ],
    dataSubject: [
        "employees",
        "internalservice",
        "customers",
        "suppliers",
        "partners",
        "serviceproviders",
        "potentialcustomer",
        "applications",
        "others",
    ],
    retentionPeriod: [
        "1",
        "3",
        "6",
        "12",
        "24",
        "36",
        "72",
    ],
    recipientType: [
        "internaldepartment",
        "processors",
        "thirdcountry",
        "commercialpartner",
        "other"
    ],
    guarantee: [
        "scc",
        "dpf",
        "bcr",
        "contryprotection",
        "privacyshield",
        "codeofconduct",
        "certification",
        "derogations",
        "none"
    ],
    toms: [
        "traceabilitymeasures",
        "softwareprotectionmeasures",
        "databackup",
        "dataencryption",
        "useraccesscontrol",
        "controlofprocessors",
        "mvps",
        "securitycert",
        "othermeasures"
    ],
}

export const steps = [
  'descriptionStakeholders',
  'purposeAndCategories',
  'recipients',
  'transfer',
  'securityMeasuresTOMs',
  'dataProtectionImpactAssessment'
];

export const fields = [
    "reviewDate",
    "controller",
    "dpo",
    "purpose",
    "category",
    "specialcategory",
    "datasubject",
    "retentionperiod",
    "commentsretention",
    "recipientType",
    "recipientdetails",
    "datatransfer",
    "recipient",
    "country",
    "guarantee",
    "toms",
    "involveProfiling",
    "useAutomated",
    "involveSurveillance",
    "processedSpecialCategories",
    "isBigData",
    "dataSetsCombined",
    "multipleControllers",
    "imbalanceInRelationship",
    "innovativeTechnologyUsed",
    "transferredOutside",
    "rightsRestricted",
    "piaNeeded",
]